export interface Question {
  id: string;
  question: string;
  options: string[];
  correctAnswer: string;
  explanation?: string;
  category: string;
  chapterId: number;
  isBoss?: boolean;
}

export const CHAPTER_QUESTIONS: Record<number, Question[]> = {
  1: [
    {
      id: "1-q1",
      chapterId: 1,
      category: "Geography",
      question: "Which is the largest continent on Earth by land area?",
      options: ["Africa", "Asia", "North America", "Antarctica"],
      correctAnswer: "Asia",
      explanation: "Asia is the largest continent, covering about 30% of Earth's land area and home to over 60% of the world's population.",
    },
    {
      id: "1-q2",
      chapterId: 1,
      category: "Geography",
      question: "What is the longest river in the world?",
      options: ["Amazon River", "Yangtze River", "Nile River", "Mississippi River"],
      correctAnswer: "Nile River",
      explanation: "The Nile, flowing through northeastern Africa, is traditionally regarded as the longest river at roughly 6,650 km.",
    },
    {
      id: "1-q3",
      chapterId: 1,
      category: "Geography",
      question: "Which line divides the Earth into the Northern and Southern Hemispheres?",
      options: ["The Prime Meridian", "The Tropic of Cancer", "The Equator", "The Arctic Circle"],
      correctAnswer: "The Equator",
      explanation: "The Equator is an imaginary line at 0 degrees latitude that splits the planet into the Northern and Southern Hemispheres.",
    },
    {
      id: "1-q4",
      chapterId: 1,
      category: "Geography",
      question: "What is the largest ocean on Earth?",
      options: ["Atlantic Ocean", "Indian Ocean", "Arctic Ocean", "Pacific Ocean"],
      correctAnswer: "Pacific Ocean",
      explanation: "The Pacific Ocean is the largest and deepest of Earth's oceans, covering more area than all land combined.",
    },
    {
      id: "1-q5",
      chapterId: 1,
      category: "Geography",
      question: "How many continents are there on Earth?",
      options: ["Five", "Six", "Seven", "Eight"],
      correctAnswer: "Seven",
      explanation: "The seven continents are Asia, Africa, North America, South America, Antarctica, Europe, and Australia.",
    },
    {
      id: "1-q6",
      chapterId: 1,
      category: "Geography",
      question: "Which desert is the largest hot desert in the world?",
      options: ["Gobi Desert", "Sahara Desert", "Kalahari Desert", "Mojave Desert"],
      correctAnswer: "Sahara Desert",
      explanation: "The Sahara in North Africa is the largest hot desert, spanning roughly 9.2 million square kilometers.",
    },
    {
      id: "1-q7",
      chapterId: 1,
      category: "Geography",
      question: "What is the tallest mountain above sea level on Earth?",
      options: ["K2", "Mount Kilimanjaro", "Mount Everest", "Denali"],
      correctAnswer: "Mount Everest",
      explanation: "Mount Everest, in the Himalayas, reaches about 8,849 meters above sea level — the highest point on Earth.",
    },
    {
      id: "1-q8",
      chapterId: 1,
      category: "Geography",
      question: "Which country is both the smallest and least populated in the world?",
      options: ["Monaco", "Vatican City", "San Marino", "Liechtenstein"],
      correctAnswer: "Vatican City",
      explanation: "Vatican City is the world's smallest independent state by both area (about 44 hectares) and population.",
    },
    {
      id: "1-boss",
      chapterId: 1,
      category: "Geography",
      isBoss: true,
      question: "The supercontinent that existed before the modern continents drifted apart was called what?",
      options: ["Gondwana", "Laurasia", "Pangaea", "Rodinia"],
      correctAnswer: "Pangaea",
      explanation: "Pangaea was a supercontinent that formed about 335 million years ago and began breaking apart around 175 million years ago.",
    },
  ],
  2: [
    {
      id: "2-q1",
      chapterId: 2,
      category: "Ancient History",
      question: "Which ancient civilization built the pyramids of Giza?",
      options: ["The Romans", "The Greeks", "The Egyptians", "The Persians"],
      correctAnswer: "The Egyptians",
      explanation: "The ancient Egyptians built the Giza pyramids around 4,500 years ago as monumental tombs for their pharaohs.",
    },
    {
      id: "2-q2",
      chapterId: 2,
      category: "Ancient History",
      question: "The Colosseum, a giant amphitheater, is located in which modern city?",
      options: ["Athens", "Rome", "Istanbul", "Cairo"],
      correctAnswer: "Rome",
      explanation: "The Colosseum was completed in 80 AD in Rome and could hold tens of thousands of spectators for public events.",
    },
    {
      id: "2-q3",
      chapterId: 2,
      category: "Ancient History",
      question: "Which river was central to the rise of ancient Mesopotamian civilization?",
      options: ["The Nile", "The Tigris and Euphrates", "The Indus", "The Yangtze"],
      correctAnswer: "The Tigris and Euphrates",
      explanation: "Mesopotamia, meaning 'land between rivers,' developed between the Tigris and Euphrates in modern-day Iraq.",
    },
    {
      id: "2-q4",
      chapterId: 2,
      category: "Ancient History",
      question: "The ancient city of Machu Picchu was built by which civilization?",
      options: ["The Aztecs", "The Maya", "The Inca", "The Olmec"],
      correctAnswer: "The Inca",
      explanation: "Machu Picchu, perched in the Peruvian Andes, was built by the Inca around the 15th century.",
    },
    {
      id: "2-q5",
      chapterId: 2,
      category: "Ancient History",
      question: "Which ancient wonder was a giant lighthouse located in Egypt?",
      options: ["The Hanging Gardens", "The Lighthouse of Alexandria", "The Colossus of Rhodes", "The Temple of Artemis"],
      correctAnswer: "The Lighthouse of Alexandria",
      explanation: "The Lighthouse of Alexandria was one of the Seven Wonders of the Ancient World, guiding ships into the harbor for centuries.",
    },
    {
      id: "2-q6",
      chapterId: 2,
      category: "Ancient History",
      question: "What writing system did the ancient Egyptians use?",
      options: ["Cuneiform", "Hieroglyphics", "Latin script", "Sanskrit"],
      correctAnswer: "Hieroglyphics",
      explanation: "Egyptian hieroglyphics combined logographic and alphabetic elements, often carved into temple and tomb walls.",
    },
    {
      id: "2-q7",
      chapterId: 2,
      category: "Ancient History",
      question: "The Great Wall was primarily built to protect which ancient empire?",
      options: ["Japan", "India", "China", "Mongolia"],
      correctAnswer: "China",
      explanation: "The Great Wall of China was built and rebuilt over centuries to defend Chinese states against northern invasions.",
    },
    {
      id: "2-q8",
      chapterId: 2,
      category: "Ancient History",
      question: "Which ancient Greek city-state is considered the birthplace of democracy?",
      options: ["Sparta", "Athens", "Corinth", "Thebes"],
      correctAnswer: "Athens",
      explanation: "Athens developed an early form of direct democracy in the 5th century BC, where citizens voted on laws directly.",
    },
    {
      id: "2-boss",
      chapterId: 2,
      category: "Ancient History",
      isBoss: true,
      question: "The Rosetta Stone was key to deciphering Egyptian hieroglyphics because it featured the same text in how many scripts?",
      options: ["Two", "Three", "Four", "Five"],
      correctAnswer: "Three",
      explanation: "The Rosetta Stone displays the same decree in three scripts: hieroglyphic, Demotic, and ancient Greek, allowing scholars to crack hieroglyphics.",
    },
  ],
  3: [
    {
      id: "3-q1",
      chapterId: 3,
      category: "Legends & Leaders",
      question: "Who was the first President of the United States?",
      options: ["Thomas Jefferson", "Abraham Lincoln", "George Washington", "John Adams"],
      correctAnswer: "George Washington",
      explanation: "George Washington served as the first U.S. President from 1789 to 1797 and is often called the 'Father of His Country.'",
    },
    {
      id: "3-q2",
      chapterId: 3,
      category: "Legends & Leaders",
      question: "Which leader is famous for leading India's nonviolent independence movement?",
      options: ["Jawaharlal Nehru", "Mahatma Gandhi", "Subhas Chandra Bose", "B. R. Ambedkar"],
      correctAnswer: "Mahatma Gandhi",
      explanation: "Mahatma Gandhi championed nonviolent civil disobedience, helping India gain independence from British rule in 1947.",
    },
    {
      id: "3-q3",
      chapterId: 3,
      category: "Legends & Leaders",
      question: "Who was the Egyptian queen known for her alliances with Julius Caesar and Mark Antony?",
      options: ["Nefertiti", "Hatshepsut", "Cleopatra", "Isis"],
      correctAnswer: "Cleopatra",
      explanation: "Cleopatra VII was the last active ruler of the Ptolemaic Kingdom of Egypt, renowned for her political alliances with Rome.",
    },
    {
      id: "3-q4",
      chapterId: 3,
      category: "Legends & Leaders",
      question: "Which South African leader became president after spending 27 years in prison?",
      options: ["Desmond Tutu", "Nelson Mandela", "Thabo Mbeki", "Jacob Zuma"],
      correctAnswer: "Nelson Mandela",
      explanation: "Nelson Mandela was imprisoned for 27 years before becoming South Africa's first democratically elected president in 1994.",
    },
    {
      id: "3-q5",
      chapterId: 3,
      category: "Legends & Leaders",
      question: "Who developed the theory of general relativity?",
      options: ["Isaac Newton", "Galileo Galilei", "Albert Einstein", "Niels Bohr"],
      correctAnswer: "Albert Einstein",
      explanation: "Albert Einstein published his theory of general relativity in 1915, reshaping our understanding of gravity, space, and time.",
    },
    {
      id: "3-q6",
      chapterId: 3,
      category: "Legends & Leaders",
      question: "Which explorer led the first expedition to circumnavigate the globe?",
      options: ["Christopher Columbus", "Vasco da Gama", "Ferdinand Magellan", "Marco Polo"],
      correctAnswer: "Ferdinand Magellan",
      explanation: "Magellan's expedition (1519-1522) was the first to circumnavigate the globe, though he died before it was completed.",
    },
    {
      id: "3-q7",
      chapterId: 3,
      category: "Legends & Leaders",
      question: "Who was the British Prime Minister during most of World War II?",
      options: ["Neville Chamberlain", "Winston Churchill", "Clement Attlee", "Anthony Eden"],
      correctAnswer: "Winston Churchill",
      explanation: "Winston Churchill led Britain through most of World War II, known for his defiant speeches and wartime leadership.",
    },
    {
      id: "3-q8",
      chapterId: 3,
      category: "Legends & Leaders",
      question: "Which scientist discovered radioactivity research and won two Nobel Prizes?",
      options: ["Rosalind Franklin", "Marie Curie", "Ada Lovelace", "Lise Meitner"],
      correctAnswer: "Marie Curie",
      explanation: "Marie Curie won Nobel Prizes in both Physics (1903) and Chemistry (1911) for her pioneering work on radioactivity.",
    },
    {
      id: "3-boss",
      chapterId: 3,
      category: "Legends & Leaders",
      isBoss: true,
      question: "Which Macedonian king created one of history's largest empires by his early thirties and never lost a battle?",
      options: ["Julius Caesar", "Alexander the Great", "Genghis Khan", "Hannibal"],
      correctAnswer: "Alexander the Great",
      explanation: "Alexander the Great built an empire stretching from Greece to India by age 30 and is famed for never losing a battle.",
    },
  ],
  4: [
    {
      id: "4-q1",
      chapterId: 4,
      category: "Culture & Traditions",
      question: "Which country is the origin of the festival 'Diwali', the festival of lights?",
      options: ["China", "India", "Thailand", "Japan"],
      correctAnswer: "India",
      explanation: "Diwali, the Hindu festival of lights, originated in India and symbolizes the victory of light over darkness.",
    },
    {
      id: "4-q2",
      chapterId: 4,
      category: "Culture & Traditions",
      question: "Sushi, a dish of vinegared rice with seafood, originates from which country?",
      options: ["China", "South Korea", "Japan", "Vietnam"],
      correctAnswer: "Japan",
      explanation: "Modern sushi developed in Japan, where it evolved into the rice-and-seafood delicacy enjoyed worldwide today.",
    },
    {
      id: "4-q3",
      chapterId: 4,
      category: "Culture & Traditions",
      question: "The traditional dance 'Flamenco' is associated with which country?",
      options: ["Italy", "Portugal", "Spain", "Mexico"],
      correctAnswer: "Spain",
      explanation: "Flamenco is an expressive art form of song, dance, and guitar that originated in the Andalusia region of Spain.",
    },
    {
      id: "4-q4",
      chapterId: 4,
      category: "Culture & Traditions",
      question: "Which festival, famous for its colorful parades and samba, is held annually in Brazil?",
      options: ["Oktoberfest", "Carnival", "Holi", "Mardi Gras"],
      correctAnswer: "Carnival",
      explanation: "Brazil's Carnival, especially in Rio de Janeiro, is world-renowned for its samba parades, music, and elaborate costumes.",
    },
    {
      id: "4-q5",
      chapterId: 4,
      category: "Culture & Traditions",
      question: "The dish 'pasta' is most closely associated with which country's cuisine?",
      options: ["France", "Italy", "Greece", "Spain"],
      correctAnswer: "Italy",
      explanation: "Pasta is a cornerstone of Italian cuisine, with countless regional shapes and sauces enjoyed across the country.",
    },
    {
      id: "4-q6",
      chapterId: 4,
      category: "Culture & Traditions",
      question: "Which traditional garment is the 'kimono', worn on special occasions?",
      options: ["A Korean robe", "A Japanese robe", "A Chinese robe", "An Indian robe"],
      correctAnswer: "A Japanese robe",
      explanation: "The kimono is a traditional Japanese garment characterized by wide sleeves and a sash called an obi.",
    },
    {
      id: "4-q7",
      chapterId: 4,
      category: "Culture & Traditions",
      question: "Day of the Dead (Dia de los Muertos) is a famous celebration in which country?",
      options: ["Spain", "Mexico", "Peru", "Argentina"],
      correctAnswer: "Mexico",
      explanation: "Dia de los Muertos is a Mexican holiday honoring deceased loved ones with altars, marigolds, and festive remembrance.",
    },
    {
      id: "4-q8",
      chapterId: 4,
      category: "Culture & Traditions",
      question: "Which musical instrument is traditionally associated with Scottish culture?",
      options: ["The accordion", "The bagpipes", "The banjo", "The sitar"],
      correctAnswer: "The bagpipes",
      explanation: "The Great Highland bagpipe is an iconic symbol of Scottish heritage, often played at ceremonies and celebrations.",
    },
    {
      id: "4-boss",
      chapterId: 4,
      category: "Culture & Traditions",
      isBoss: true,
      question: "Which language has the most native speakers in the world?",
      options: ["English", "Hindi", "Spanish", "Mandarin Chinese"],
      correctAnswer: "Mandarin Chinese",
      explanation: "Mandarin Chinese has the largest number of native speakers, with around one billion people speaking it as a first language.",
    },
  ],
  5: [
    {
      id: "5-q1",
      chapterId: 5,
      category: "World Challenge",
      question: "What is the capital city of Australia?",
      options: ["Sydney", "Melbourne", "Canberra", "Perth"],
      correctAnswer: "Canberra",
      explanation: "Canberra is Australia's purpose-built capital, chosen as a compromise between rivals Sydney and Melbourne.",
    },
    {
      id: "5-q2",
      chapterId: 5,
      category: "World Challenge",
      question: "Which planet in our solar system is known as the Red Planet?",
      options: ["Venus", "Jupiter", "Mars", "Mercury"],
      correctAnswer: "Mars",
      explanation: "Mars appears red because of iron oxide (rust) covering much of its surface.",
    },
    {
      id: "5-q3",
      chapterId: 5,
      category: "World Challenge",
      question: "Which country has the largest population in the world?",
      options: ["China", "United States", "Indonesia", "India"],
      correctAnswer: "India",
      explanation: "India became the world's most populous country in 2023, surpassing China with over 1.4 billion people.",
    },
    {
      id: "5-q4",
      chapterId: 5,
      category: "World Challenge",
      question: "What is the currency used in Japan?",
      options: ["Won", "Yuan", "Yen", "Ringgit"],
      correctAnswer: "Yen",
      explanation: "The Japanese yen is the official currency of Japan and one of the most traded currencies in the world.",
    },
    {
      id: "5-q5",
      chapterId: 5,
      category: "World Challenge",
      question: "Which famous painting by Leonardo da Vinci hangs in the Louvre?",
      options: ["The Starry Night", "The Scream", "The Mona Lisa", "Guernica"],
      correctAnswer: "The Mona Lisa",
      explanation: "The Mona Lisa, painted by Leonardo da Vinci in the early 1500s, is one of the most famous artworks in the world.",
    },
    {
      id: "5-q6",
      chapterId: 5,
      category: "World Challenge",
      question: "Mount Fuji is the highest mountain in which country?",
      options: ["China", "South Korea", "Japan", "Nepal"],
      correctAnswer: "Japan",
      explanation: "Mount Fuji, an active volcano rising 3,776 meters, is Japan's tallest peak and a cultural icon.",
    },
    {
      id: "5-q7",
      chapterId: 5,
      category: "World Challenge",
      question: "Which country gifted the Statue of Liberty to the United States?",
      options: ["United Kingdom", "France", "Spain", "Italy"],
      correctAnswer: "France",
      explanation: "France gifted the Statue of Liberty to the United States in 1886 as a symbol of friendship and freedom.",
    },
    {
      id: "5-q8",
      chapterId: 5,
      category: "World Challenge",
      question: "What is the smallest planet in our solar system?",
      options: ["Mars", "Mercury", "Venus", "Pluto"],
      correctAnswer: "Mercury",
      explanation: "Mercury is the smallest planet in the solar system and the closest to the Sun. (Pluto is classified as a dwarf planet.)",
    },
    {
      id: "5-boss",
      chapterId: 5,
      category: "World Challenge",
      isBoss: true,
      question: "Which international organization, founded in 1945, aims to maintain global peace and security?",
      options: ["NATO", "The European Union", "The United Nations", "The World Bank"],
      correctAnswer: "The United Nations",
      explanation: "The United Nations was founded in 1945 after World War II to promote international cooperation, peace, and security.",
    },
  ],
};

/**
 * Fetches all questions (standard + boss) for a specific chapter
 */
export const getQuestionsForChapter = async (chapterId: number): Promise<Question[]> => {
  return CHAPTER_QUESTIONS[chapterId] || [];
};
